server:
  port: 8088

logging:
  level:
    org.springframework: debug

spring:
  messages:
    basename: messages
#  security:
#    user:
#      name: username
#      password: passw0rd
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    show-sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test # test 부분을 자신이 원하는 것으로 바꾸시면 됩니다.
    username: sa # username과 password는 자신의 설정에 맞게
    password:
    driver-class-name: org.h2.Driver


management:
  endpoints:
    web:
      exposure:
        include: "*"